### PR TITLE
MU3.6 compliant

### PR DESCRIPTION
**Pull request by lgvr123**
- MU3.6 compliant
- Correct closing mechanism

### CODE REVIEW

**Review by Ash-86 — CHANGES_REQUESTED** [review]
The arrow heads on the note name and accidental combo boxes (for invert by specific pitch) have gone missing in 4x. Could you please fix those?

Also, window.close() doesn't seem to stop the plugin. You have to manually quit the plugin (at least in the plugin creator in 3x). Why then is this better than Qt.quit()?

**Comment by Ash-86** [comment]
Thanks, I'll test it in a bit. You did not answer my second question thought...

**Comment by lgvr123** [comment]
> The arrow heads on the note name and accidental combo boxes (for invert by specific pitch) have gone missing in 4x. Could you please fix those?

The missing arrows are back.
As you redefined all your components by tweaking colours, the sizes, the result was not ideal in MU3.6 light mode. 
I saw you stared using the SystemPalette but abandoned. It is usually a great way to deal with the light and the dark modes. However, the dark mode is bugged in MU3.6 and some text don't render in the right colour.
If you like using customised components (which I do too), you should opt for creating your own reusable components that you store in a subfolder. Once defined, you can reuse it everywhere in your `.qml` file merely by replacing `RadioButton` by `MyRadioButton`. This approach would greatly simplify your plugin UI part.

> Also, window.close() doesn't seem to stop the plugin. You have to manually quit the plugin (at least in the plugin creator in 3x). Why then is this better than Qt.quit()?

`Qt.quit()` crashes and MU4.x and is not recommended in MU3.6.
See [this post](https://musescore.org/en/node/304874#comment-1001236) for the reason why.

**Comment by lgvr123** [comment]
This one ?
> Also, window.close() doesn't seem to stop the plugin

This is a non-issue. With `window.close()` the plugin is closed, even it seems to still be running in the Editor.

`Qt.quit()` must be definitely avoided, because it stops Qt and _de facto_ closes all other running plugin instances.
 
Little demo, with 2 dock-type plugin ([Annotations](https://musescore.org/en/project/annotations) and [Mixer Minimalist Style](https://musescore.org/en/project/mixer-minimalistic-style)) and one dialog-type plugin:

QtQuit

A mere `Qt.quit()` and all the other plugin is stopped. This is a No-Show for every plugin using the function.

**Comment by Ash-86** [comment]
Qt.quit indeed closes other plugins, quit() however in 4x does not. But i see how window.close() is a safer approach nonetheless. 
I originally wanted to use SystemPalette to adapt to both light and dark themes but i had some trouble with that and thought I'd keep it for a later upgrade (this is my first Qt project so i probably just coudn't figure it out, i'm sure it is simple), but anyway I decided to go about it from scratch. I know i should've made a separate file for the radioButtons, I think I was just lazy really.. I might as well do it for the sake of having a clearer code for future upgrades and modifications. Thanks for the tip anyway:)

By the way, I'm not sure the 4x style UI looked great on 3.6. I think I would prefer the plain UI In the tranformer3x file. But i guess it is also good to have a single file for both 3x and 4x. 

Cheers Igvr123!

**Pull request merged**
